[project]
name = "claudrond"
description = "A simple, ligthweight and secure python scheduler for UNIX systems that does not depend on any third-party packages."
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "solarvenom" }]
license = { text = "MIT" }
dynamic = ["version"]

[project.scripts]
claudrond = "claudrond.__main__:main"

[project.urls]
"Homepage" = "https://github.com/solarvenom/claudrond"
"Issue Tracker" = "https://github.com/solarvenom/claudrond/issues"

[tool.pyright]
pythonPlatform = "All"

[tool.setuptools_scm]