# date_formats: list[str] = [
#     "%Y-%m-%d",
#     "%d/%m/%Y",
#     "%m-%d-%Y",
#     "%B %d, %Y",
#     "%b %d, %Y",
#     "%d-%b-%Y",
#     "%Y/%m/%d",
#     "%d %B %Y",
#     "%A, %B %d, %Y",
#     "%Y-%m-%d %H:%M:%S",
#     "%d/%m/%Y %I:%M %p",
#     "%m-%d-%Y %H:%M",
#     "%d %b %Y, %H:%M:%S",
#     "%B %d, %Y at %I:%M %p",
#     "%Y/%m/%d %H:%M:%S.%f",
#     "%a, %d %b %Y %H:%M:%S",
#     "%A, %d %B %Y, %I:%M %p",
#     "%Y%m%dT%H%M%S",
#     "%H:%M:%S on %d/%m/%Y",
#     "%Y-%m-%d %H:%M:%S %Z",
#     "%Y-%m-%d %H:%M:%S %z",
#     "%Y-%m-%dT%H:%M:%S%z",
#     "%Y-%m-%dT%H:%M:%S.%f%z",
#     "%Y-%m-%dT%H:%M:%S"
# ]